### ISSUE TITLE
Ship a new version?

### ISSUE THREAD

**Issue by colszowka** [technion/ruby-argon2#11]
Hey there,

thanks for your work on this! I tried out the library and it seems the API changed significantly on master in comparison to 0.1.4 on Rubygems, most notably the examples mentioning `create` do not work since the method has been renamed from `hash`. It would be nice to have a new version shipped so the README on the Github landing page actually matches what you get upon installing the lib.

Cheers!

**Comment by technion** [comment]
Hi,

There is slight hold up here unfortunately. There is currently [a branch in the reference C library](https://github.com/P-H-C/phc-winner-argon2/tree/1.3)  that makes major breaking changes, and will definitely require a major version bump. I'm attempting to avoid tagging version 1.0.0 (to address to move to 'create') and then releasing version 2.0.0 a few days later when that gets merged.

For background on the API change you noticed, refer to #9.

I'm definitely aware of this issue - which is why I already bumped version.rb and was literally hours away from shipping it when I came across this issue.

**Comment by colszowka** [comment]
@technion Thanks for the info! I whipped up a tiny PR at #12 that adds a disclaimer note to the README on master

**Comment by technion** [comment]
Thanks! I'll take that PR as a close on this issue. Discussion on the PHC issues page suggests this should hit mainline soon. Note, it breaks literally every test case, so I'll be burning some time importing it.

**Comment by colszowka** [comment]
Thanks for your efforts!

**Comment by technion** [comment]
@colszowka  I know this is closed but just to update you - I've pulled in the 1.3 algorithm and updated all tests. I'll just give it a few more days while they debate API stabilisation before tagging.
