### ISSUE TITLE
Lack of null-byte support (limitation of encodings)

### ISSUE THREAD

**Issue by tgoddard** [technion/ruby-argon2#2]
The current implementation requires that this passes the password as a c-string without a length, so no null bytes can exist in the password string. This may seriously limit, for example, the ability to use this on strings in some encodings (UTF-16).

**Comment by technion** [comment]
Hi,

I note this is regardless with the Python bindings, which refuse UTF-8, and, up until a few days ago, were shipped with the reference implementation.

Regardless, you're correct, I'll be getting this fixed.

**Comment by technion** [comment]
I have pushed a fix that addresses this. This probably deserves a version bump, will leave this open a few days to settle first.

I've put the codebase successfully through:

    $ TEST_CHECKS=10000 bundle exec rake test

That said, any effort spent Googling regarding UTF-16 and Ruby only ever seems to lead to bugs, from RSpec, to Rails, to Ruby core. I can only guarantee what's covered in the tests, which is why d16c291 happened.
